env:
  GITHUB_TOKEN: ${{ secrets.PULUMI_BOT_TOKEN }}

name: OSS SDK Files
on:
  schedule:
    - cron: '0 4 * * *'
  repository_dispatch:
    types:
      - oss-sdk
  workflow_dispatch:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    needs: prepare-sdk
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: checkout nextgen provider repo
        uses: actions/checkout@v2
        with:
          repository: pulumi/pulumi-azure-nextgen-provider
          path: provider
          ref: master
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
      - name: Initialize Submodules
        run: git submodule update --init
        working-directory: provider/azure-rest-api-specs
      - name: Git submodule commit hash
        id: vars
        run: echo ::set-output name=commit-hash::$(git rev-parse HEAD)
        working-directory: provider/azure-rest-api-specs
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "publish/${{ github.run_id }}-${{ github.run_number }}"
          destination_branch: "master"
          pr_title: "Publish SDK @ azure-rest-api-specs ${{ steps.vars.outputs.commit-hash }}"
          pr_body: "*Automated PR*"
          pr_label: "automation/merge"
          pr_allow_empty: true
          github_token: ${{ secrets.PULUMI_BOT_TOKEN }}
  prepare-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          path: sdk-repo
      - name: checkout nextgen provider repo
        uses: actions/checkout@v2
        with:
          repository: pulumi/pulumi-azure-nextgen-provider
          path: provider
          ref: master
          token: ${{ secrets.PULUMI_BOT_TOKEN }}
      - name: prepare sdk files
        run: |
          rm -rf ${{ github.workspace }}/sdk-repo/sdk
          cp -R sdk/ ${{ github.workspace }}/sdk-repo
          rm -f ${{ github.workspace }}/sdk-repo/sdk/SDK_LICENSE
          touch ${{ github.workspace }}/sdk-repo/sdk/nodejs/go.mod
          touch ${{ github.workspace }}/sdk-repo/sdk/python/go.mod
          touch ${{ github.workspace }}/sdk-repo/sdk/dotnet/go.mod
        working-directory: provider
      - name: Git Commit + Push to Branch
        run: |
          git config --local user.email "bot@pulumi.com"
          git config --local user.name "pulumi-bot"
          git checkout -b publish/${{ github.run_id }}-${{ github.run_number }}
          git commit -a -m "Automated SDK publish"
          git push origin publish/${{ github.run_id }}-${{ github.run_number }}
        working-directory: ${{ github.workspace }}/sdk-repo
